sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tAcMv4qghH7Qpufenxm
    access-key-secret: BSg0QpNjoy5rzX3DBedFk72MHQPDkR
    bucket-name: web-tlias-mobai
  redis:
    host: 47.120.9.108
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wxbc0b078a4ca8d008
    secret: df896f1a16f1921ed396e712411ad4e8
