sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tAcMv4qghH7Qpufenxm
    access-key-secret: BSg0QpNjoy5rzX3DBedFk72MHQPDkR
    bucket-name: web-tlias-mobai
